// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/PauloHFS/goth/internal/db"
	"github.com/PauloHFS/goth/internal/view/layout"
	"github.com/PauloHFS/goth/web/components"
)

func Admin(user *db.User) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"py-8\"><div class=\"mx-auto max-w-7xl px-4 sm:px-6 lg:px-8\"><!-- Header --><div class=\"mb-8\"><h1 class=\"text-3xl font-bold text-gray-900 dark:text-white\">Admin Dashboard</h1><p class=\"mt-2 text-gray-600 dark:text-gray-400\">System overview and monitoring</p></div><!-- Stats Grid --><div class=\"grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4 mb-8\"><div class=\"bg-white dark:bg-zinc-900 rounded-xl border border-gray-200 dark:border-gray-800 p-6\"><div class=\"flex items-center\"><div class=\"inline-flex h-12 w-12 items-center justify-center rounded-lg bg-blue-100 dark:bg-blue-900/30\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.LucideIcon("users", "h-6 w-6 text-blue-600 dark:text-blue-400").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><div class=\"ml-4\"><p class=\"text-sm font-medium text-gray-500 dark:text-gray-400\">Total Users</p><p class=\"text-2xl font-semibold text-gray-900 dark:text-white\" id=\"total-users\">--</p></div></div></div><div class=\"bg-white dark:bg-zinc-900 rounded-xl border border-gray-200 dark:border-gray-800 p-6\"><div class=\"flex items-center\"><div class=\"inline-flex h-12 w-12 items-center justify-center rounded-lg bg-green-100 dark:bg-green-900/30\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.LucideIcon("check-circle", "h-6 w-6 text-green-600 dark:text-green-400").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div class=\"ml-4\"><p class=\"text-sm font-medium text-gray-500 dark:text-gray-400\">Active Sessions</p><p class=\"text-2xl font-semibold text-gray-900 dark:text-white\" id=\"active-sessions\">--</p></div></div></div><div class=\"bg-white dark:bg-zinc-900 rounded-xl border border-gray-200 dark:border-gray-800 p-6\"><div class=\"flex items-center\"><div class=\"inline-flex h-12 w-12 items-center justify-center rounded-lg bg-yellow-100 dark:bg-yellow-900/30\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.LucideIcon("clock", "h-6 w-6 text-yellow-600 dark:text-yellow-400").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><div class=\"ml-4\"><p class=\"text-sm font-medium text-gray-500 dark:text-gray-400\">Pending Jobs</p><p class=\"text-2xl font-semibold text-gray-900 dark:text-white\" id=\"pending-jobs\">--</p></div></div></div><div class=\"bg-white dark:bg-zinc-900 rounded-xl border border-gray-200 dark:border-gray-800 p-6\"><div class=\"flex items-center\"><div class=\"inline-flex h-12 w-12 items-center justify-center rounded-lg bg-red-100 dark:bg-red-900/30\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.LucideIcon("alert-triangle", "h-6 w-6 text-red-600 dark:text-red-400").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><div class=\"ml-4\"><p class=\"text-sm font-medium text-gray-500 dark:text-gray-400\">DLQ Jobs</p><p class=\"text-2xl font-semibold text-gray-900 dark:text-white\" id=\"dlq-jobs\">--</p></div></div></div></div><!-- Quick Links --><div class=\"grid grid-cols-1 gap-6 lg:grid-cols-2\"><div class=\"bg-white dark:bg-zinc-900 rounded-xl border border-gray-200 dark:border-gray-800 p-6\"><h2 class=\"text-lg font-semibold text-gray-900 dark:text-white mb-4\">Quick Actions</h2><div class=\"space-y-3\"><a href=\"/admin/users\" class=\"flex items-center justify-between p-3 rounded-lg border border-gray-200 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-zinc-800 transition-colors\"><span class=\"text-gray-700 dark:text-gray-300\">Manage Users</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.LucideIcon("chevron-right", "h-5 w-5 text-gray-400").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</a> <a href=\"/admin/dlq\" class=\"flex items-center justify-between p-3 rounded-lg border border-gray-200 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-zinc-800 transition-colors\"><span class=\"text-gray-700 dark:text-gray-300\">Dead Letter Queue</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.LucideIcon("chevron-right", "h-5 w-5 text-gray-400").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</a> <a href=\"/admin/workers\" class=\"flex items-center justify-between p-3 rounded-lg border border-gray-200 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-zinc-800 transition-colors\"><span class=\"text-gray-700 dark:text-gray-300\">Worker Status</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.LucideIcon("chevron-right", "h-5 w-5 text-gray-400").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</a></div></div><div class=\"bg-white dark:bg-zinc-900 rounded-xl border border-gray-200 dark:border-gray-800 p-6\"><h2 class=\"text-lg font-semibold text-gray-900 dark:text-white mb-4\">System Health</h2><div class=\"space-y-4\" id=\"system-health\"><div class=\"flex items-center justify-between\"><span class=\"text-gray-700 dark:text-gray-300\">Database</span> <span class=\"inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400\">Checking...</span></div><div class=\"flex items-center justify-between\"><span class=\"text-gray-700 dark:text-gray-300\">Cache</span> <span class=\"inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400\">Checking...</span></div><div class=\"flex items-center justify-between\"><span class=\"text-gray-700 dark:text-gray-300\">Job Queue</span> <span class=\"inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400\">Checking...</span></div></div></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Base("Admin Dashboard - GOTH Stack", db.Tenant{Name: "GOTH Stack"}, user).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
