// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/PauloHFS/goth/internal/db"
	"github.com/PauloHFS/goth/internal/view/layout"
	"github.com/PauloHFS/goth/web/components"
)

func Pricing(user *db.User) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"py-20\"><div class=\"mx-auto max-w-7xl px-4 sm:px-6 lg:px-8\"><!-- Header --><div class=\"text-center mb-16\"><h1 class=\"text-4xl font-bold tracking-tight text-gray-900 dark:text-white sm:text-5xl\">Simple, transparent pricing</h1><p class=\"mt-4 text-xl text-gray-600 dark:text-gray-400\">Choose the plan that fits your needs. No hidden fees.</p></div><!-- Pricing Cards --><div class=\"grid grid-cols-1 gap-8 lg:grid-cols-3\"><!-- Free Plan --><div class=\"relative rounded-2xl border border-gray-200 bg-white p-8 dark:border-gray-800 dark:bg-zinc-900\"><h3 class=\"text-lg font-semibold leading-8 text-gray-900 dark:text-white\">Free</h3><p class=\"mt-4 text-sm leading-6 text-gray-600 dark:text-gray-400\">Perfect for hobby projects</p><p class=\"mt-6 flex items-baseline gap-x-1\"><span class=\"text-4xl font-bold tracking-tight text-gray-900 dark:text-white\">$0</span> <span class=\"text-sm font-semibold leading-6 text-gray-600 dark:text-gray-400\">/month</span></p><ul role=\"list\" class=\"mt-8 space-y-3 text-sm leading-6 text-gray-600 dark:text-gray-400\"><li class=\"flex gap-x-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.LucideIcon("check", "h-6 w-5 flex-none text-gray-900 dark:text-white").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "1 user</li><li class=\"flex gap-x-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.LucideIcon("check", "h-6 w-5 flex-none text-gray-900 dark:text-white").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "1,000 API requests/month</li><li class=\"flex gap-x-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.LucideIcon("check", "h-6 w-5 flex-none text-gray-900 dark:text-white").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "100MB storage</li><li class=\"flex gap-x-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.LucideIcon("check", "h-6 w-5 flex-none text-gray-900 dark:text-white").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "Community support</li></ul><a href=\"/register\" class=\"mt-8 block rounded-xl bg-gray-100 px-3 py-2 text-center text-sm font-semibold text-gray-900 hover:bg-gray-200 dark:bg-zinc-800 dark:text-white dark:hover:bg-zinc-700 transition-colors\">Get Started Free</a></div><!-- Pro Plan --><div class=\"relative rounded-2xl border border-gray-900 bg-gray-900 p-8 dark:border-white dark:bg-white\"><h3 class=\"text-lg font-semibold leading-8 text-white dark:text-gray-900\">Pro</h3><p class=\"mt-4 text-sm leading-6 text-gray-300 dark:text-gray-600\">For growing teams</p><p class=\"mt-6 flex items-baseline gap-x-1\"><span class=\"text-4xl font-bold tracking-tight text-white dark:text-gray-900\">$29</span> <span class=\"text-sm font-semibold leading-6 text-gray-300 dark:text-gray-600\">/month</span></p><ul role=\"list\" class=\"mt-8 space-y-3 text-sm leading-6 text-gray-300 dark:text-gray-600\"><li class=\"flex gap-x-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.LucideIcon("check", "h-6 w-5 flex-none text-white dark:text-gray-900").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "Up to 10 users</li><li class=\"flex gap-x-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.LucideIcon("check", "h-6 w-5 flex-none text-white dark:text-gray-900").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "100,000 API requests/month</li><li class=\"flex gap-x-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.LucideIcon("check", "h-6 w-5 flex-none text-white dark:text-gray-900").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "10GB storage</li><li class=\"flex gap-x-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.LucideIcon("check", "h-6 w-5 flex-none text-white dark:text-gray-900").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "Priority email support</li><li class=\"flex gap-x-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.LucideIcon("check", "h-6 w-5 flex-none text-white dark:text-gray-900").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "Advanced analytics</li></ul><a href=\"/register?plan=pro\" class=\"mt-8 block rounded-xl bg-white px-3 py-2 text-center text-sm font-semibold text-gray-900 hover:bg-gray-100 dark:bg-gray-900 dark:text-white dark:hover:bg-gray-800 transition-colors\">Start Pro Trial</a></div><!-- Enterprise Plan --><div class=\"relative rounded-2xl border border-gray-200 bg-white p-8 dark:border-gray-800 dark:bg-zinc-900\"><h3 class=\"text-lg font-semibold leading-8 text-gray-900 dark:text-white\">Enterprise</h3><p class=\"mt-4 text-sm leading-6 text-gray-600 dark:text-gray-400\">For large organizations</p><p class=\"mt-6 flex items-baseline gap-x-1\"><span class=\"text-4xl font-bold tracking-tight text-gray-900 dark:text-white\">Custom</span></p><ul role=\"list\" class=\"mt-8 space-y-3 text-sm leading-6 text-gray-600 dark:text-gray-400\"><li class=\"flex gap-x-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.LucideIcon("check", "h-6 w-5 flex-none text-gray-900 dark:text-white").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "Unlimited users</li><li class=\"flex gap-x-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.LucideIcon("check", "h-6 w-5 flex-none text-gray-900 dark:text-white").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "Unlimited API requests</li><li class=\"flex gap-x-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.LucideIcon("check", "h-6 w-5 flex-none text-gray-900 dark:text-white").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "Unlimited storage</li><li class=\"flex gap-x-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.LucideIcon("check", "h-6 w-5 flex-none text-gray-900 dark:text-white").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "24/7 dedicated support</li><li class=\"flex gap-x-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.LucideIcon("check", "h-6 w-5 flex-none text-gray-900 dark:text-white").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "Custom integrations</li></ul><a href=\"/contact\" class=\"mt-8 block rounded-xl bg-gray-100 px-3 py-2 text-center text-sm font-semibold text-gray-900 hover:bg-gray-200 dark:bg-zinc-800 dark:text-white dark:hover:bg-zinc-700 transition-colors\">Contact Sales</a></div></div><!-- FAQ Section --><div class=\"mt-24\"><h2 class=\"text-2xl font-bold tracking-tight text-gray-900 dark:text-white text-center mb-12\">Frequently Asked Questions</h2><div class=\"grid grid-cols-1 gap-8 md:grid-cols-2\"><div class=\"rounded-xl border border-gray-200 p-6 dark:border-gray-800 dark:bg-zinc-900\"><h3 class=\"text-lg font-semibold text-gray-900 dark:text-white\">Can I change plans later?</h3><p class=\"mt-2 text-gray-600 dark:text-gray-400\">Yes, you can upgrade or downgrade your plan at any time. Changes take effect immediately.</p></div><div class=\"rounded-xl border border-gray-200 p-6 dark:border-gray-800 dark:bg-zinc-900\"><h3 class=\"text-lg font-semibold text-gray-900 dark:text-white\">What payment methods do you accept?</h3><p class=\"mt-2 text-gray-600 dark:text-gray-400\">We accept all major credit cards, PayPal, and bank transfers for Enterprise plans.</p></div><div class=\"rounded-xl border border-gray-200 p-6 dark:border-gray-800 dark:bg-zinc-900\"><h3 class=\"text-lg font-semibold text-gray-900 dark:text-white\">Is there a free trial?</h3><p class=\"mt-2 text-gray-600 dark:text-gray-400\">Yes! Pro plans include a 14-day free trial. No credit card required.</p></div><div class=\"rounded-xl border border-gray-200 p-6 dark:border-gray-800 dark:bg-zinc-900\"><h3 class=\"text-lg font-semibold text-gray-900 dark:text-white\">What happens if I exceed my limits?</h3><p class=\"mt-2 text-gray-600 dark:text-gray-400\">We'll notify you before hitting limits. You can upgrade or pay for overages.</p></div></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Base("Pricing - GOTH Stack", db.Tenant{Name: "GOTH Stack"}, user).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
