run:
  timeout: 5m
  modules-download-mode: readonly

issues:
  exclude-dirs:
    - internal/db/queries
  exclude-rules:
    # Test files - relax some linters
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - revive
        - noctx
        - unused-parameter
        - rowserrcheck
    # Queries directory
    - path: internal/db/queries/
      linters:
        - all
    # Ignore fieldalignment for all files (optimization, not correctness)
    - path: .
      text: "fieldalignment"
    # Ignore goconst for strings (too aggressive)
    - path: .
      text: "goconst"
    # Ignore gocyclo warnings (complexity is OK for now)
    - path: .
      text: "cyclomatic complexity"
    # Ignore unused mutex in rate limiter (false positive)
    - path: internal/middleware/rate_limit\.go
      text: "mu.*unused"
    # Ignore Sscanf errcheck (common pattern for simple parsing)
    - path: internal/config/config\.go
      text: "Sscanf"
    # Ignore json encoder errcheck (logging/metrics)
    - path: internal/middleware/rate_limit\.go
      text: "Encode"
    # Ignore Rollback errcheck (defer pattern)
    - path: internal/worker/dead_letter\.go
      text: "Rollback"
    # Ignore string conversions in worker (acceptable)
    - path: internal/worker/
      text: "unnecessary conversion"
    # Ignore bodyclose for streaming responses (handled by caller)
    - path: internal/llm/stream\.go
      linters:
        - bodyclose
    # Ignore goimports for swagger alias
    - path: internal/cmd/server\.go
      text: "goimports"
    # Ignore rowserrcheck in vector service (error handled via context)
    - path: internal/vector/service\.go
      linters:
        - rowserrcheck

linters:
  enable:
    # Critical linters - bugs and errors
    - bodyclose
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - typecheck
    - unused
    - whitespace
    - gofmt
    - goimports
    
    # Security
    - gosec
    
    # Style (non-intrusive)
    - dogsled
    - goprintffuncname
    - nakedret
    - nolintlint
    - prealloc
    - rowserrcheck
    - unconvert

linters-settings:
  gosec:
    excludes:
      - G104  # Errors unhandled
      - G115  # Integer overflow (false positives)
      - G404  # Weak random (acceptable for jitter/backoff)
      - G112  # Slowloris (acceptable for simple boilerplate)
