// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/feature-flags": {
            "get": {
                "description": "Returns a list of all feature flags for the tenant",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feature Flags"
                ],
                "summary": "List all feature flags",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/featureflags.FeatureFlag"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new feature flag",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feature Flags"
                ],
                "summary": "Create feature flag",
                "parameters": [
                    {
                        "description": "Feature flag data",
                        "name": "flag",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/featureflags.FeatureFlagInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/featureflags.FeatureFlag"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/feature-flags/check/{name}": {
            "get": {
                "description": "Checks if a feature flag is enabled",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feature Flags"
                ],
                "summary": "Check feature flag status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feature flag name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/feature-flags/{id}": {
            "put": {
                "description": "Updates an existing feature flag",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feature Flags"
                ],
                "summary": "Update feature flag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Feature flag ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Feature flag data",
                        "name": "flag",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/featureflags.FeatureFlagInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/featureflags.FeatureFlag"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a feature flag",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feature Flags"
                ],
                "summary": "Delete feature flag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Feature flag ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/feature-flags/{id}/toggle": {
            "post": {
                "description": "Toggles a feature flag enabled/disabled state",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feature Flags"
                ],
                "summary": "Toggle feature flag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Feature flag ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/featureflags.FeatureFlag"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/feature-flags/{name}": {
            "get": {
                "description": "Returns a specific feature flag by name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feature Flags"
                ],
                "summary": "Get feature flag by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feature flag name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/featureflags.FeatureFlag"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/log-level": {
            "get": {
                "description": "Returns the current application log level",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logging"
                ],
                "summary": "Get current log level",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/logging.LevelResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Sets the application log level dynamically",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logging"
                ],
                "summary": "Set log level",
                "parameters": [
                    {
                        "description": "New log level (debug, info, warn, error)",
                        "name": "level",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/logging.LevelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/logging.LevelResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/secrets/reload": {
            "post": {
                "description": "Forces a manual reload of secrets from .env file",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Secrets"
                ],
                "summary": "Reload secrets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/secrets/rotate": {
            "post": {
                "description": "Rotates a specific secret (in-memory only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Secrets"
                ],
                "summary": "Rotate secret",
                "parameters": [
                    {
                        "description": "Secret type and new value",
                        "name": "secret",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/secrets.RotateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/secrets/status": {
            "get": {
                "description": "Returns the current status of the secret manager",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Secrets"
                ],
                "summary": "Get secrets status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/secrets.Status"
                        }
                    }
                }
            }
        },
        "/checkout/subscribe": {
            "post": {
                "description": "Creates a new payment/subscription",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Billing"
                ],
                "summary": "Subscribe to plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Plan value in cents",
                        "name": "plan_value",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Billing type (PIX, BOLETO, CREDIT_CARD)",
                        "name": "billing_type",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/billing.PaymentResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/events": {
            "get": {
                "description": "Establishes Server-Sent Events connection for real-time notifications",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "Real-time"
                ],
                "summary": "SSE notifications",
                "responses": {
                    "200": {
                        "description": "SSE stream",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/forgot-password": {
            "get": {
                "description": "Displays the password recovery form",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Show forgot password form",
                "responses": {
                    "200": {
                        "description": "Forgot password form HTML",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Sends password reset email if user exists",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Request password reset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Confirmation message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "get": {
                "description": "Displays the user login form",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Show login form",
                "responses": {
                    "200": {
                        "description": "Login form HTML",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Authenticates user and creates session",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login form with error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "303": {
                        "description": "Redirect to dashboard on success"
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "description": "Destroys user session and redirects to login",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Logout user",
                "responses": {
                    "303": {
                        "description": "Redirect to login"
                    }
                }
            }
        },
        "/register": {
            "get": {
                "description": "Displays the user registration form",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Show registration form",
                "responses": {
                    "200": {
                        "description": "Registration form HTML",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new user account",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Register new user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Registration form with error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "303": {
                        "description": "Redirect to login on success"
                    }
                }
            }
        },
        "/reset-password": {
            "get": {
                "description": "Displays the password reset form with token",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Show reset password form",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Reset token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Reset password form HTML",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Resets user password using valid token",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Reset password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Reset token",
                        "name": "token",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "New password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Reset form with error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "303": {
                        "description": "Redirect to login on success"
                    }
                }
            }
        },
        "/verify-email": {
            "get": {
                "description": "Verifies user email using token",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Verify email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Verification token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "303": {
                        "description": "Redirect to login with success message"
                    }
                }
            }
        },
        "/webhook/asaas": {
            "post": {
                "description": "Processes payment webhooks from Asaas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Billing"
                ],
                "summary": "Process Asaas webhook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Webhook signature",
                        "name": "asaas-hmac-sha256",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "billing.PaymentResult": {
            "type": "object",
            "properties": {
                "invoiceUrl": {
                    "type": "string"
                },
                "paymentId": {
                    "type": "string"
                },
                "pixCopyPaste": {
                    "type": "string"
                },
                "pixQrCode": {
                    "type": "string"
                }
            }
        },
        "featureflags.FeatureFlag": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "metadata": {
                    "description": "JSON adicional para config",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "featureflags.FeatureFlagInput": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "metadata": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                }
            }
        },
        "logging.LevelRequest": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "string"
                }
            }
        },
        "logging.LevelResponse": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "string"
                }
            }
        },
        "secrets.RotateRequest": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "secrets.Status": {
            "type": "object",
            "properties": {
                "last_reload": {
                    "type": "string"
                },
                "missing_secrets": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "secrets_loaded": {
                    "type": "integer"
                },
                "watcher_enabled": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
