// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: core.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const completeJob = `-- name: CompleteJob :exec
UPDATE jobs 
SET status = 'completed', updated_at = CURRENT_TIMESTAMP 
WHERE id = ?
`

func (q *Queries) CompleteJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, completeJob, id)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users WHERE tenant_id = ?
`

func (q *Queries) CountUsers(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsaasCustomer = `-- name: CreateAsaasCustomer :one

INSERT INTO asaas_customers (id, tenant_id, user_id, email, cpf_cnpj, name, asaas_data)
VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, tenant_id, user_id, email, cpf_cnpj, name, asaas_data, created_at, updated_at
`

type CreateAsaasCustomerParams struct {
	ID        string          `json:"id"`
	TenantID  string          `json:"tenant_id"`
	UserID    sql.NullInt64   `json:"user_id"`
	Email     string          `json:"email"`
	CpfCnpj   sql.NullString  `json:"cpf_cnpj"`
	Name      sql.NullString  `json:"name"`
	AsaasData json.RawMessage `json:"asaas_data"`
}

// Asaas Customers
func (q *Queries) CreateAsaasCustomer(ctx context.Context, arg CreateAsaasCustomerParams) (AsaasCustomer, error) {
	row := q.db.QueryRowContext(ctx, createAsaasCustomer,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Email,
		arg.CpfCnpj,
		arg.Name,
		arg.AsaasData,
	)
	var i AsaasCustomer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Email,
		&i.CpfCnpj,
		&i.Name,
		&i.AsaasData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAsaasPayment = `-- name: CreateAsaasPayment :one

INSERT INTO asaas_payments (id, tenant_id, customer_id, user_id, amount, billing_type, status, due_date, invoice_url, invoice_id, pix_qr_code, pix_copy_paste, asaas_response)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, tenant_id, customer_id, user_id, amount, billing_type, status, due_date, payment_date, invoice_url, invoice_id, pix_qr_code, pix_copy_paste, asaas_response, created_at, updated_at
`

type CreateAsaasPaymentParams struct {
	ID            string          `json:"id"`
	TenantID      string          `json:"tenant_id"`
	CustomerID    string          `json:"customer_id"`
	UserID        sql.NullInt64   `json:"user_id"`
	Amount        float64         `json:"amount"`
	BillingType   string          `json:"billing_type"`
	Status        string          `json:"status"`
	DueDate       time.Time       `json:"due_date"`
	InvoiceUrl    sql.NullString  `json:"invoice_url"`
	InvoiceID     sql.NullString  `json:"invoice_id"`
	PixQrCode     sql.NullString  `json:"pix_qr_code"`
	PixCopyPaste  sql.NullString  `json:"pix_copy_paste"`
	AsaasResponse json.RawMessage `json:"asaas_response"`
}

// Asaas Payments
func (q *Queries) CreateAsaasPayment(ctx context.Context, arg CreateAsaasPaymentParams) (AsaasPayment, error) {
	row := q.db.QueryRowContext(ctx, createAsaasPayment,
		arg.ID,
		arg.TenantID,
		arg.CustomerID,
		arg.UserID,
		arg.Amount,
		arg.BillingType,
		arg.Status,
		arg.DueDate,
		arg.InvoiceUrl,
		arg.InvoiceID,
		arg.PixQrCode,
		arg.PixCopyPaste,
		arg.AsaasResponse,
	)
	var i AsaasPayment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.UserID,
		&i.Amount,
		&i.BillingType,
		&i.Status,
		&i.DueDate,
		&i.PaymentDate,
		&i.InvoiceUrl,
		&i.InvoiceID,
		&i.PixQrCode,
		&i.PixCopyPaste,
		&i.AsaasResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAsaasSubscription = `-- name: CreateAsaasSubscription :one

INSERT INTO asaas_subscriptions (id, tenant_id, customer_id, user_id, plan_value, billing_type, cycle_type, status, next_billing_date, asaas_response)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, tenant_id, customer_id, user_id, plan_value, billing_type, cycle_type, status, next_billing_date, asaas_response, created_at, updated_at
`

type CreateAsaasSubscriptionParams struct {
	ID              string          `json:"id"`
	TenantID        string          `json:"tenant_id"`
	CustomerID      string          `json:"customer_id"`
	UserID          sql.NullInt64   `json:"user_id"`
	PlanValue       float64         `json:"plan_value"`
	BillingType     string          `json:"billing_type"`
	CycleType       string          `json:"cycle_type"`
	Status          string          `json:"status"`
	NextBillingDate sql.NullTime    `json:"next_billing_date"`
	AsaasResponse   json.RawMessage `json:"asaas_response"`
}

// Asaas Subscriptions
func (q *Queries) CreateAsaasSubscription(ctx context.Context, arg CreateAsaasSubscriptionParams) (AsaasSubscription, error) {
	row := q.db.QueryRowContext(ctx, createAsaasSubscription,
		arg.ID,
		arg.TenantID,
		arg.CustomerID,
		arg.UserID,
		arg.PlanValue,
		arg.BillingType,
		arg.CycleType,
		arg.Status,
		arg.NextBillingDate,
		arg.AsaasResponse,
	)
	var i AsaasSubscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.UserID,
		&i.PlanValue,
		&i.BillingType,
		&i.CycleType,
		&i.Status,
		&i.NextBillingDate,
		&i.AsaasResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDeadLetterJob = `-- name: CreateDeadLetterJob :one

INSERT INTO dead_letter_jobs (job_id, original_type, original_payload, error_message, attempt_count, tenant_id, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, job_id, original_type, original_payload, error_message, attempt_count, failed_at, tenant_id, metadata
`

type CreateDeadLetterJobParams struct {
	JobID           int64           `json:"job_id"`
	OriginalType    string          `json:"original_type"`
	OriginalPayload json.RawMessage `json:"original_payload"`
	ErrorMessage    string          `json:"error_message"`
	AttemptCount    int64           `json:"attempt_count"`
	TenantID        sql.NullString  `json:"tenant_id"`
	Metadata        json.RawMessage `json:"metadata"`
}

// Dead Letter Queue
func (q *Queries) CreateDeadLetterJob(ctx context.Context, arg CreateDeadLetterJobParams) (DeadLetterJob, error) {
	row := q.db.QueryRowContext(ctx, createDeadLetterJob,
		arg.JobID,
		arg.OriginalType,
		arg.OriginalPayload,
		arg.ErrorMessage,
		arg.AttemptCount,
		arg.TenantID,
		arg.Metadata,
	)
	var i DeadLetterJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.OriginalType,
		&i.OriginalPayload,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.FailedAt,
		&i.TenantID,
		&i.Metadata,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (tenant_id, type, payload, run_at, idempotency_key) 
VALUES (?, ?, ?, ?, ?) 
RETURNING id, tenant_id, type, payload, status, idempotency_key, attempt_count, max_attempts, last_error, run_at, next_retry_at, worker_id, started_at, completed_at, timeout_seconds, priority, created_at, updated_at
`

type CreateJobParams struct {
	TenantID       sql.NullString  `json:"tenant_id"`
	Type           string          `json:"type"`
	Payload        json.RawMessage `json:"payload"`
	RunAt          sql.NullTime    `json:"run_at"`
	IdempotencyKey sql.NullString  `json:"idempotency_key"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.TenantID,
		arg.Type,
		arg.Payload,
		arg.RunAt,
		arg.IdempotencyKey,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.IdempotencyKey,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LastError,
		&i.RunAt,
		&i.NextRetryAt,
		&i.WorkerID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TimeoutSeconds,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJobWithIdempotency = `-- name: CreateJobWithIdempotency :one
INSERT INTO jobs (tenant_id, type, payload, run_at, idempotency_key) 
VALUES (?, ?, ?, ?, ?) 
ON CONFLICT(idempotency_key) DO UPDATE SET 
    updated_at = CURRENT_TIMESTAMP
RETURNING id, tenant_id, type, payload, status, idempotency_key, attempt_count, max_attempts, last_error, run_at, next_retry_at, worker_id, started_at, completed_at, timeout_seconds, priority, created_at, updated_at
`

type CreateJobWithIdempotencyParams struct {
	TenantID       sql.NullString  `json:"tenant_id"`
	Type           string          `json:"type"`
	Payload        json.RawMessage `json:"payload"`
	RunAt          sql.NullTime    `json:"run_at"`
	IdempotencyKey sql.NullString  `json:"idempotency_key"`
}

func (q *Queries) CreateJobWithIdempotency(ctx context.Context, arg CreateJobWithIdempotencyParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJobWithIdempotency,
		arg.TenantID,
		arg.Type,
		arg.Payload,
		arg.RunAt,
		arg.IdempotencyKey,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.IdempotencyKey,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LastError,
		&i.RunAt,
		&i.NextRetryAt,
		&i.WorkerID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TimeoutSeconds,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProcessedWebhookEvent = `-- name: CreateProcessedWebhookEvent :exec

INSERT INTO processed_webhook_events (event_source, event_id, webhook_id)
VALUES (?, ?, ?)
ON CONFLICT(event_source, event_id) DO UPDATE SET
    processed_at = CURRENT_TIMESTAMP
`

type CreateProcessedWebhookEventParams struct {
	EventSource string        `json:"event_source"`
	EventID     string        `json:"event_id"`
	WebhookID   sql.NullInt64 `json:"webhook_id"`
}

// Processed Webhook Events (Idempotency)
func (q *Queries) CreateProcessedWebhookEvent(ctx context.Context, arg CreateProcessedWebhookEventParams) error {
	_, err := q.db.ExecContext(ctx, createProcessedWebhookEvent, arg.EventSource, arg.EventID, arg.WebhookID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, email, password_hash, role_id) 
VALUES (?, ?, ?, ?) RETURNING id, tenant_id, email, password_hash, role_id, is_verified, avatar_url, created_at, provider, provider_id
`

type CreateUserParams struct {
	TenantID     string `json:"tenant_id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	RoleID       string `json:"role_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.RoleID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.RoleID,
		&i.IsVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.Provider,
		&i.ProviderID,
	)
	return i, err
}

const createUserWithOAuth = `-- name: CreateUserWithOAuth :one
INSERT INTO users (tenant_id, email, provider, provider_id, password_hash, role_id, is_verified, avatar_url)
VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, tenant_id, email, password_hash, role_id, is_verified, avatar_url, created_at, provider, provider_id
`

type CreateUserWithOAuthParams struct {
	TenantID     string         `json:"tenant_id"`
	Email        string         `json:"email"`
	Provider     sql.NullString `json:"provider"`
	ProviderID   sql.NullString `json:"provider_id"`
	PasswordHash string         `json:"password_hash"`
	RoleID       string         `json:"role_id"`
	IsVerified   bool           `json:"is_verified"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
}

func (q *Queries) CreateUserWithOAuth(ctx context.Context, arg CreateUserWithOAuthParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUserWithOAuth,
		arg.TenantID,
		arg.Email,
		arg.Provider,
		arg.ProviderID,
		arg.PasswordHash,
		arg.RoleID,
		arg.IsVerified,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.RoleID,
		&i.IsVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.Provider,
		&i.ProviderID,
	)
	return i, err
}

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (source, external_id, payload, headers)
VALUES (?, ?, ?, ?) RETURNING id, source, external_id, payload, headers, status, created_at
`

type CreateWebhookParams struct {
	Source     string          `json:"source"`
	ExternalID sql.NullString  `json:"external_id"`
	Payload    json.RawMessage `json:"payload"`
	Headers    json.RawMessage `json:"headers"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, createWebhook,
		arg.Source,
		arg.ExternalID,
		arg.Payload,
		arg.Headers,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Payload,
		&i.Headers,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createWebhookWithIdempotency = `-- name: CreateWebhookWithIdempotency :one
INSERT INTO webhooks (source, external_id, payload, headers, status)
VALUES (?, ?, ?, ?, 'pending')
ON CONFLICT(source, external_id) DO UPDATE SET
    payload = excluded.payload,
    headers = excluded.headers,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, source, external_id, payload, headers, status, created_at
`

type CreateWebhookWithIdempotencyParams struct {
	Source     string          `json:"source"`
	ExternalID sql.NullString  `json:"external_id"`
	Payload    json.RawMessage `json:"payload"`
	Headers    json.RawMessage `json:"headers"`
}

func (q *Queries) CreateWebhookWithIdempotency(ctx context.Context, arg CreateWebhookWithIdempotencyParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, createWebhookWithIdempotency,
		arg.Source,
		arg.ExternalID,
		arg.Payload,
		arg.Headers,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Payload,
		&i.Headers,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDeadLetterJob = `-- name: DeleteDeadLetterJob :exec
DELETE FROM dead_letter_jobs WHERE id = ?
`

func (q *Queries) DeleteDeadLetterJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDeadLetterJob, id)
	return err
}

const deleteEmailVerification = `-- name: DeleteEmailVerification :exec
DELETE FROM email_verifications WHERE email = ?
`

func (q *Queries) DeleteEmailVerification(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deleteEmailVerification, email)
	return err
}

const deletePasswordReset = `-- name: DeletePasswordReset :exec
DELETE FROM password_resets WHERE email = ?
`

func (q *Queries) DeletePasswordReset(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deletePasswordReset, email)
	return err
}

const failJob = `-- name: FailJob :exec
UPDATE jobs SET status = 'failed', last_error = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type FailJobParams struct {
	LastError sql.NullString `json:"last_error"`
	ID        int64          `json:"id"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.ExecContext(ctx, failJob, arg.LastError, arg.ID)
	return err
}

const getActiveSubscriptionByUser = `-- name: GetActiveSubscriptionByUser :one
SELECT id, tenant_id, customer_id, user_id, plan_value, billing_type, cycle_type, status, next_billing_date, asaas_response, created_at, updated_at FROM asaas_subscriptions WHERE user_id = ? AND status = 'ACTIVE' LIMIT 1
`

func (q *Queries) GetActiveSubscriptionByUser(ctx context.Context, userID sql.NullInt64) (AsaasSubscription, error) {
	row := q.db.QueryRowContext(ctx, getActiveSubscriptionByUser, userID)
	var i AsaasSubscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.UserID,
		&i.PlanValue,
		&i.BillingType,
		&i.CycleType,
		&i.Status,
		&i.NextBillingDate,
		&i.AsaasResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAsaasCustomerByEmail = `-- name: GetAsaasCustomerByEmail :one
SELECT id, tenant_id, user_id, email, cpf_cnpj, name, asaas_data, created_at, updated_at FROM asaas_customers WHERE tenant_id = ? AND email = ? LIMIT 1
`

type GetAsaasCustomerByEmailParams struct {
	TenantID string `json:"tenant_id"`
	Email    string `json:"email"`
}

func (q *Queries) GetAsaasCustomerByEmail(ctx context.Context, arg GetAsaasCustomerByEmailParams) (AsaasCustomer, error) {
	row := q.db.QueryRowContext(ctx, getAsaasCustomerByEmail, arg.TenantID, arg.Email)
	var i AsaasCustomer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Email,
		&i.CpfCnpj,
		&i.Name,
		&i.AsaasData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAsaasCustomerByID = `-- name: GetAsaasCustomerByID :one
SELECT id, tenant_id, user_id, email, cpf_cnpj, name, asaas_data, created_at, updated_at FROM asaas_customers WHERE id = ? LIMIT 1
`

func (q *Queries) GetAsaasCustomerByID(ctx context.Context, id string) (AsaasCustomer, error) {
	row := q.db.QueryRowContext(ctx, getAsaasCustomerByID, id)
	var i AsaasCustomer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Email,
		&i.CpfCnpj,
		&i.Name,
		&i.AsaasData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAsaasPaymentByID = `-- name: GetAsaasPaymentByID :one
SELECT id, tenant_id, customer_id, user_id, amount, billing_type, status, due_date, payment_date, invoice_url, invoice_id, pix_qr_code, pix_copy_paste, asaas_response, created_at, updated_at FROM asaas_payments WHERE id = ? LIMIT 1
`

func (q *Queries) GetAsaasPaymentByID(ctx context.Context, id string) (AsaasPayment, error) {
	row := q.db.QueryRowContext(ctx, getAsaasPaymentByID, id)
	var i AsaasPayment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.UserID,
		&i.Amount,
		&i.BillingType,
		&i.Status,
		&i.DueDate,
		&i.PaymentDate,
		&i.InvoiceUrl,
		&i.InvoiceID,
		&i.PixQrCode,
		&i.PixCopyPaste,
		&i.AsaasResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAsaasSubscriptionByID = `-- name: GetAsaasSubscriptionByID :one
SELECT id, tenant_id, customer_id, user_id, plan_value, billing_type, cycle_type, status, next_billing_date, asaas_response, created_at, updated_at FROM asaas_subscriptions WHERE id = ? LIMIT 1
`

func (q *Queries) GetAsaasSubscriptionByID(ctx context.Context, id string) (AsaasSubscription, error) {
	row := q.db.QueryRowContext(ctx, getAsaasSubscriptionByID, id)
	var i AsaasSubscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.UserID,
		&i.PlanValue,
		&i.BillingType,
		&i.CycleType,
		&i.Status,
		&i.NextBillingDate,
		&i.AsaasResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCircuitBreakerState = `-- name: GetCircuitBreakerState :one

SELECT job_type, state, failure_count, success_count, last_failure_at, last_success_at, opened_at, updated_at FROM circuit_breaker_states WHERE job_type = ?
`

// Circuit Breaker
func (q *Queries) GetCircuitBreakerState(ctx context.Context, jobType string) (CircuitBreakerState, error) {
	row := q.db.QueryRowContext(ctx, getCircuitBreakerState, jobType)
	var i CircuitBreakerState
	err := row.Scan(
		&i.JobType,
		&i.State,
		&i.FailureCount,
		&i.SuccessCount,
		&i.LastFailureAt,
		&i.LastSuccessAt,
		&i.OpenedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeadLetterJobCount = `-- name: GetDeadLetterJobCount :one
SELECT COUNT(*) FROM dead_letter_jobs
`

func (q *Queries) GetDeadLetterJobCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDeadLetterJobCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDeadLetterJobs = `-- name: GetDeadLetterJobs :many
SELECT id, job_id, original_type, original_payload, error_message, attempt_count, failed_at, tenant_id, metadata FROM dead_letter_jobs ORDER BY failed_at DESC LIMIT ? OFFSET ?
`

type GetDeadLetterJobsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) GetDeadLetterJobs(ctx context.Context, arg GetDeadLetterJobsParams) ([]DeadLetterJob, error) {
	rows, err := q.db.QueryContext(ctx, getDeadLetterJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeadLetterJob
	for rows.Next() {
		var i DeadLetterJob
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.OriginalType,
			&i.OriginalPayload,
			&i.ErrorMessage,
			&i.AttemptCount,
			&i.FailedAt,
			&i.TenantID,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmailVerificationByToken = `-- name: GetEmailVerificationByToken :one
SELECT email, token, expires_at, created_at FROM email_verifications WHERE token = ? LIMIT 1
`

func (q *Queries) GetEmailVerificationByToken(ctx context.Context, token string) (EmailVerification, error) {
	row := q.db.QueryRowContext(ctx, getEmailVerificationByToken, token)
	var i EmailVerification
	err := row.Scan(
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, tenant_id, type, payload, status, idempotency_key, attempt_count, max_attempts, last_error, run_at, next_retry_at, worker_id, started_at, completed_at, timeout_seconds, priority, created_at, updated_at FROM jobs WHERE id = ? LIMIT 1
`

func (q *Queries) GetJobByID(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.IdempotencyKey,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LastError,
		&i.RunAt,
		&i.NextRetryAt,
		&i.WorkerID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TimeoutSeconds,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobMetricsHourly = `-- name: GetJobMetricsHourly :many
SELECT hour, job_type, total_processed, total_succeeded, total_failed, avg_duration_ms, min_duration_ms, max_duration_ms, updated_at FROM job_metrics_hourly WHERE hour >= ? ORDER BY hour DESC LIMIT ?
`

type GetJobMetricsHourlyParams struct {
	Hour  string `json:"hour"`
	Limit int64  `json:"limit"`
}

func (q *Queries) GetJobMetricsHourly(ctx context.Context, arg GetJobMetricsHourlyParams) ([]JobMetricsHourly, error) {
	rows, err := q.db.QueryContext(ctx, getJobMetricsHourly, arg.Hour, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobMetricsHourly
	for rows.Next() {
		var i JobMetricsHourly
		if err := rows.Scan(
			&i.Hour,
			&i.JobType,
			&i.TotalProcessed,
			&i.TotalSucceeded,
			&i.TotalFailed,
			&i.AvgDurationMs,
			&i.MinDurationMs,
			&i.MaxDurationMs,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobTypeConfig = `-- name: GetJobTypeConfig :one

SELECT job_type, timeout_seconds, max_attempts, backoff_base_seconds, backoff_max_seconds, enabled, updated_at FROM job_type_configs WHERE job_type = ?
`

// Job Type Configs
func (q *Queries) GetJobTypeConfig(ctx context.Context, jobType string) (JobTypeConfig, error) {
	row := q.db.QueryRowContext(ctx, getJobTypeConfig, jobType)
	var i JobTypeConfig
	err := row.Scan(
		&i.JobType,
		&i.TimeoutSeconds,
		&i.MaxAttempts,
		&i.BackoffBaseSeconds,
		&i.BackoffMaxSeconds,
		&i.Enabled,
		&i.UpdatedAt,
	)
	return i, err
}

const getPasswordResetByToken = `-- name: GetPasswordResetByToken :one
SELECT email, token_hash, expires_at, created_at FROM password_resets WHERE token_hash = ? LIMIT 1
`

func (q *Queries) GetPasswordResetByToken(ctx context.Context, tokenHash string) (PasswordReset, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetByToken, tokenHash)
	var i PasswordReset
	err := row.Scan(
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingJobCount = `-- name: GetPendingJobCount :one

SELECT COUNT(*) FROM jobs WHERE status = 'pending' AND run_at <= CURRENT_TIMESTAMP
`

// Job Notification (para otimizar polling)
func (q *Queries) GetPendingJobCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPendingJobCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProcessedWebhookEvent = `-- name: GetProcessedWebhookEvent :one
SELECT event_source, event_id, webhook_id, processed_at FROM processed_webhook_events WHERE event_source = ? AND event_id = ? LIMIT 1
`

type GetProcessedWebhookEventParams struct {
	EventSource string `json:"event_source"`
	EventID     string `json:"event_id"`
}

func (q *Queries) GetProcessedWebhookEvent(ctx context.Context, arg GetProcessedWebhookEventParams) (ProcessedWebhookEvent, error) {
	row := q.db.QueryRowContext(ctx, getProcessedWebhookEvent, arg.EventSource, arg.EventID)
	var i ProcessedWebhookEvent
	err := row.Scan(
		&i.EventSource,
		&i.EventID,
		&i.WebhookID,
		&i.ProcessedAt,
	)
	return i, err
}

const getStaleProcessingJobs = `-- name: GetStaleProcessingJobs :many

SELECT id, tenant_id, type, payload, status, idempotency_key, attempt_count, max_attempts, last_error, run_at, next_retry_at, worker_id, started_at, completed_at, timeout_seconds, priority, created_at, updated_at FROM jobs 
WHERE status = 'processing' 
AND started_at < datetime('now', '-' || CAST(? AS TEXT) || ' seconds')
ORDER BY started_at ASC
`

// Job Timeout Management
func (q *Queries) GetStaleProcessingJobs(ctx context.Context, dollar_1 string) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, getStaleProcessingJobs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.Payload,
			&i.Status,
			&i.IdempotencyKey,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.LastError,
			&i.RunAt,
			&i.NextRetryAt,
			&i.WorkerID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TimeoutSeconds,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, settings, created_at FROM tenants WHERE id = ? LIMIT 1
`

func (q *Queries) GetTenantByID(ctx context.Context, id string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, password_hash, role_id, is_verified, avatar_url, created_at, provider, provider_id FROM users WHERE tenant_id = ? AND email = ? LIMIT 1
`

type GetUserByEmailParams struct {
	TenantID string `json:"tenant_id"`
	Email    string `json:"email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, arg.TenantID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.RoleID,
		&i.IsVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.Provider,
		&i.ProviderID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, password_hash, role_id, is_verified, avatar_url, created_at, provider, provider_id FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.RoleID,
		&i.IsVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.Provider,
		&i.ProviderID,
	)
	return i, err
}

const getUserByProvider = `-- name: GetUserByProvider :one

SELECT id, tenant_id, email, password_hash, role_id, is_verified, avatar_url, created_at, provider, provider_id FROM users WHERE tenant_id = ? AND provider = ? AND provider_id = ? LIMIT 1
`

type GetUserByProviderParams struct {
	TenantID   string         `json:"tenant_id"`
	Provider   sql.NullString `json:"provider"`
	ProviderID sql.NullString `json:"provider_id"`
}

// OAuth2 Queries
func (q *Queries) GetUserByProvider(ctx context.Context, arg GetUserByProviderParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByProvider, arg.TenantID, arg.Provider, arg.ProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.RoleID,
		&i.IsVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.Provider,
		&i.ProviderID,
	)
	return i, err
}

const getWebhookByID = `-- name: GetWebhookByID :one
SELECT id, source, external_id, payload, headers, status, created_at FROM webhooks WHERE id = ? LIMIT 1
`

func (q *Queries) GetWebhookByID(ctx context.Context, id int64) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhookByID, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Payload,
		&i.Headers,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const isJobProcessed = `-- name: IsJobProcessed :one
SELECT EXISTS(SELECT 1 FROM processed_jobs WHERE job_id = ?)
`

func (q *Queries) IsJobProcessed(ctx context.Context, jobID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, isJobProcessed, jobID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const isWebhookEventProcessed = `-- name: IsWebhookEventProcessed :one
SELECT EXISTS(SELECT 1 FROM processed_webhook_events WHERE event_source = ? AND event_id = ?)
`

type IsWebhookEventProcessedParams struct {
	EventSource string `json:"event_source"`
	EventID     string `json:"event_id"`
}

func (q *Queries) IsWebhookEventProcessed(ctx context.Context, arg IsWebhookEventProcessedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isWebhookEventProcessed, arg.EventSource, arg.EventID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listAsaasPaymentsByCustomer = `-- name: ListAsaasPaymentsByCustomer :many
SELECT id, tenant_id, customer_id, user_id, amount, billing_type, status, due_date, payment_date, invoice_url, invoice_id, pix_qr_code, pix_copy_paste, asaas_response, created_at, updated_at FROM asaas_payments WHERE customer_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListAsaasPaymentsByCustomer(ctx context.Context, customerID string) ([]AsaasPayment, error) {
	rows, err := q.db.QueryContext(ctx, listAsaasPaymentsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AsaasPayment
	for rows.Next() {
		var i AsaasPayment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.UserID,
			&i.Amount,
			&i.BillingType,
			&i.Status,
			&i.DueDate,
			&i.PaymentDate,
			&i.InvoiceUrl,
			&i.InvoiceID,
			&i.PixQrCode,
			&i.PixCopyPaste,
			&i.AsaasResponse,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAsaasPaymentsByUser = `-- name: ListAsaasPaymentsByUser :many
SELECT id, tenant_id, customer_id, user_id, amount, billing_type, status, due_date, payment_date, invoice_url, invoice_id, pix_qr_code, pix_copy_paste, asaas_response, created_at, updated_at FROM asaas_payments WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListAsaasPaymentsByUser(ctx context.Context, userID sql.NullInt64) ([]AsaasPayment, error) {
	rows, err := q.db.QueryContext(ctx, listAsaasPaymentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AsaasPayment
	for rows.Next() {
		var i AsaasPayment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.UserID,
			&i.Amount,
			&i.BillingType,
			&i.Status,
			&i.DueDate,
			&i.PaymentDate,
			&i.InvoiceUrl,
			&i.InvoiceID,
			&i.PixQrCode,
			&i.PixCopyPaste,
			&i.AsaasResponse,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAsaasSubscriptionsByCustomer = `-- name: ListAsaasSubscriptionsByCustomer :many
SELECT id, tenant_id, customer_id, user_id, plan_value, billing_type, cycle_type, status, next_billing_date, asaas_response, created_at, updated_at FROM asaas_subscriptions WHERE customer_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListAsaasSubscriptionsByCustomer(ctx context.Context, customerID string) ([]AsaasSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listAsaasSubscriptionsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AsaasSubscription
	for rows.Next() {
		var i AsaasSubscription
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.UserID,
			&i.PlanValue,
			&i.BillingType,
			&i.CycleType,
			&i.Status,
			&i.NextBillingDate,
			&i.AsaasResponse,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAsaasSubscriptionsByUser = `-- name: ListAsaasSubscriptionsByUser :many
SELECT id, tenant_id, customer_id, user_id, plan_value, billing_type, cycle_type, status, next_billing_date, asaas_response, created_at, updated_at FROM asaas_subscriptions WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListAsaasSubscriptionsByUser(ctx context.Context, userID sql.NullInt64) ([]AsaasSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listAsaasSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AsaasSubscription
	for rows.Next() {
		var i AsaasSubscription
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.UserID,
			&i.PlanValue,
			&i.BillingType,
			&i.CycleType,
			&i.Status,
			&i.NextBillingDate,
			&i.AsaasResponse,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCircuitBreakerStates = `-- name: ListCircuitBreakerStates :many
SELECT job_type, state, failure_count, success_count, last_failure_at, last_success_at, opened_at, updated_at FROM circuit_breaker_states ORDER BY job_type
`

func (q *Queries) ListCircuitBreakerStates(ctx context.Context) ([]CircuitBreakerState, error) {
	rows, err := q.db.QueryContext(ctx, listCircuitBreakerStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CircuitBreakerState
	for rows.Next() {
		var i CircuitBreakerState
		if err := rows.Scan(
			&i.JobType,
			&i.State,
			&i.FailureCount,
			&i.SuccessCount,
			&i.LastFailureAt,
			&i.LastSuccessAt,
			&i.OpenedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobTypeConfigs = `-- name: ListJobTypeConfigs :many
SELECT job_type, timeout_seconds, max_attempts, backoff_base_seconds, backoff_max_seconds, enabled, updated_at FROM job_type_configs ORDER BY job_type
`

func (q *Queries) ListJobTypeConfigs(ctx context.Context) ([]JobTypeConfig, error) {
	rows, err := q.db.QueryContext(ctx, listJobTypeConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobTypeConfig
	for rows.Next() {
		var i JobTypeConfig
		if err := rows.Scan(
			&i.JobType,
			&i.TimeoutSeconds,
			&i.MaxAttempts,
			&i.BackoffBaseSeconds,
			&i.BackoffMaxSeconds,
			&i.Enabled,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersPaginated = `-- name: ListUsersPaginated :many
SELECT id, tenant_id, email, password_hash, role_id, is_verified, avatar_url, created_at, provider, provider_id FROM users 
WHERE tenant_id = ? 
AND (email LIKE '%' || ? || '%' OR ? = '')
ORDER BY created_at DESC 
LIMIT ? OFFSET ?
`

type ListUsersPaginatedParams struct {
	TenantID string         `json:"tenant_id"`
	Column2  sql.NullString `json:"column_2"`
	Column3  interface{}    `json:"column_3"`
	Limit    int64          `json:"limit"`
	Offset   int64          `json:"offset"`
}

func (q *Queries) ListUsersPaginated(ctx context.Context, arg ListUsersPaginatedParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersPaginated,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.RoleID,
			&i.IsVerified,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.Provider,
			&i.ProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickNextJob = `-- name: PickNextJob :one
UPDATE jobs
SET status = 'processing', updated_at = CURRENT_TIMESTAMP, started_at = CURRENT_TIMESTAMP
WHERE id = (
    SELECT id FROM jobs
    WHERE status = 'pending'
    AND run_at <= CURRENT_TIMESTAMP
    AND (next_retry_at IS NULL OR next_retry_at <= CURRENT_TIMESTAMP)
    ORDER BY priority ASC, run_at ASC LIMIT 1
) RETURNING id, tenant_id, type, payload, status, idempotency_key, attempt_count, max_attempts, last_error, run_at, next_retry_at, worker_id, started_at, completed_at, timeout_seconds, priority, created_at, updated_at
`

func (q *Queries) PickNextJob(ctx context.Context) (Job, error) {
	row := q.db.QueryRowContext(ctx, pickNextJob)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.IdempotencyKey,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LastError,
		&i.RunAt,
		&i.NextRetryAt,
		&i.WorkerID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TimeoutSeconds,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pickNextJobWithWorker = `-- name: PickNextJobWithWorker :one
UPDATE jobs
SET status = 'processing', updated_at = CURRENT_TIMESTAMP, started_at = CURRENT_TIMESTAMP, worker_id = ?
WHERE id = (
    SELECT id FROM jobs
    WHERE status = 'pending'
    AND run_at <= CURRENT_TIMESTAMP
    AND (next_retry_at IS NULL OR next_retry_at <= CURRENT_TIMESTAMP)
    ORDER BY priority ASC, run_at ASC LIMIT 1
) RETURNING id, tenant_id, type, payload, status, idempotency_key, attempt_count, max_attempts, last_error, run_at, next_retry_at, worker_id, started_at, completed_at, timeout_seconds, priority, created_at, updated_at
`

func (q *Queries) PickNextJobWithWorker(ctx context.Context, workerID sql.NullString) (Job, error) {
	row := q.db.QueryRowContext(ctx, pickNextJobWithWorker, workerID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.IdempotencyKey,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LastError,
		&i.RunAt,
		&i.NextRetryAt,
		&i.WorkerID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TimeoutSeconds,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordJobProcessed = `-- name: RecordJobProcessed :exec
INSERT INTO processed_jobs (job_id) VALUES (?)
ON CONFLICT(job_id) DO UPDATE SET processed_at = CURRENT_TIMESTAMP
`

func (q *Queries) RecordJobProcessed(ctx context.Context, jobID int64) error {
	_, err := q.db.ExecContext(ctx, recordJobProcessed, jobID)
	return err
}

const rescueZombies = `-- name: RescueZombies :exec
UPDATE jobs 
SET status = 'pending', attempt_count = attempt_count + 1 
WHERE status = 'processing' AND updated_at < datetime('now', '-5 minutes')
`

func (q *Queries) RescueZombies(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, rescueZombies)
	return err
}

const retryDeadLetterJob = `-- name: RetryDeadLetterJob :one
INSERT INTO jobs (tenant_id, type, payload, status, run_at, attempt_count, timeout_seconds)
VALUES (?, ?, ?, 'pending', ?, ?, ?) RETURNING id, tenant_id, type, payload, status, idempotency_key, attempt_count, max_attempts, last_error, run_at, next_retry_at, worker_id, started_at, completed_at, timeout_seconds, priority, created_at, updated_at
`

type RetryDeadLetterJobParams struct {
	TenantID       sql.NullString  `json:"tenant_id"`
	Type           string          `json:"type"`
	Payload        json.RawMessage `json:"payload"`
	RunAt          sql.NullTime    `json:"run_at"`
	AttemptCount   sql.NullInt64   `json:"attempt_count"`
	TimeoutSeconds sql.NullInt64   `json:"timeout_seconds"`
}

func (q *Queries) RetryDeadLetterJob(ctx context.Context, arg RetryDeadLetterJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, retryDeadLetterJob,
		arg.TenantID,
		arg.Type,
		arg.Payload,
		arg.RunAt,
		arg.AttemptCount,
		arg.TimeoutSeconds,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.IdempotencyKey,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LastError,
		&i.RunAt,
		&i.NextRetryAt,
		&i.WorkerID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TimeoutSeconds,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const timeoutJob = `-- name: TimeoutJob :exec
UPDATE jobs 
SET status = 'failed', 
    last_error = 'Job timed out',
    updated_at = CURRENT_TIMESTAMP,
    completed_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) TimeoutJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, timeoutJob, id)
	return err
}

const updateAsaasCustomer = `-- name: UpdateAsaasCustomer :one
UPDATE asaas_customers SET cpf_cnpj = ?, name = ?, asaas_data = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? RETURNING id, tenant_id, user_id, email, cpf_cnpj, name, asaas_data, created_at, updated_at
`

type UpdateAsaasCustomerParams struct {
	CpfCnpj   sql.NullString  `json:"cpf_cnpj"`
	Name      sql.NullString  `json:"name"`
	AsaasData json.RawMessage `json:"asaas_data"`
	ID        string          `json:"id"`
}

func (q *Queries) UpdateAsaasCustomer(ctx context.Context, arg UpdateAsaasCustomerParams) (AsaasCustomer, error) {
	row := q.db.QueryRowContext(ctx, updateAsaasCustomer,
		arg.CpfCnpj,
		arg.Name,
		arg.AsaasData,
		arg.ID,
	)
	var i AsaasCustomer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Email,
		&i.CpfCnpj,
		&i.Name,
		&i.AsaasData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAsaasPaymentStatus = `-- name: UpdateAsaasPaymentStatus :one
UPDATE asaas_payments SET status = ?, payment_date = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? RETURNING id, tenant_id, customer_id, user_id, amount, billing_type, status, due_date, payment_date, invoice_url, invoice_id, pix_qr_code, pix_copy_paste, asaas_response, created_at, updated_at
`

type UpdateAsaasPaymentStatusParams struct {
	Status      string       `json:"status"`
	PaymentDate sql.NullTime `json:"payment_date"`
	ID          string       `json:"id"`
}

func (q *Queries) UpdateAsaasPaymentStatus(ctx context.Context, arg UpdateAsaasPaymentStatusParams) (AsaasPayment, error) {
	row := q.db.QueryRowContext(ctx, updateAsaasPaymentStatus, arg.Status, arg.PaymentDate, arg.ID)
	var i AsaasPayment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.UserID,
		&i.Amount,
		&i.BillingType,
		&i.Status,
		&i.DueDate,
		&i.PaymentDate,
		&i.InvoiceUrl,
		&i.InvoiceID,
		&i.PixQrCode,
		&i.PixCopyPaste,
		&i.AsaasResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAsaasSubscription = `-- name: UpdateAsaasSubscription :one
UPDATE asaas_subscriptions SET status = ?, next_billing_date = ?, asaas_response = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? RETURNING id, tenant_id, customer_id, user_id, plan_value, billing_type, cycle_type, status, next_billing_date, asaas_response, created_at, updated_at
`

type UpdateAsaasSubscriptionParams struct {
	Status          string          `json:"status"`
	NextBillingDate sql.NullTime    `json:"next_billing_date"`
	AsaasResponse   json.RawMessage `json:"asaas_response"`
	ID              string          `json:"id"`
}

func (q *Queries) UpdateAsaasSubscription(ctx context.Context, arg UpdateAsaasSubscriptionParams) (AsaasSubscription, error) {
	row := q.db.QueryRowContext(ctx, updateAsaasSubscription,
		arg.Status,
		arg.NextBillingDate,
		arg.AsaasResponse,
		arg.ID,
	)
	var i AsaasSubscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.UserID,
		&i.PlanValue,
		&i.BillingType,
		&i.CycleType,
		&i.Status,
		&i.NextBillingDate,
		&i.AsaasResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCircuitBreakerFailure = `-- name: UpdateCircuitBreakerFailure :exec
UPDATE circuit_breaker_states SET
    failure_count = failure_count + 1,
    last_failure_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE job_type = ?
`

func (q *Queries) UpdateCircuitBreakerFailure(ctx context.Context, jobType string) error {
	_, err := q.db.ExecContext(ctx, updateCircuitBreakerFailure, jobType)
	return err
}

const updateCircuitBreakerOpen = `-- name: UpdateCircuitBreakerOpen :exec
UPDATE circuit_breaker_states SET
    state = 'open',
    opened_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE job_type = ?
`

func (q *Queries) UpdateCircuitBreakerOpen(ctx context.Context, jobType string) error {
	_, err := q.db.ExecContext(ctx, updateCircuitBreakerOpen, jobType)
	return err
}

const updateCircuitBreakerSuccess = `-- name: UpdateCircuitBreakerSuccess :exec
UPDATE circuit_breaker_states SET
    failure_count = 0,
    success_count = success_count + 1,
    last_success_at = CURRENT_TIMESTAMP,
    state = 'closed',
    updated_at = CURRENT_TIMESTAMP
WHERE job_type = ?
`

func (q *Queries) UpdateCircuitBreakerSuccess(ctx context.Context, jobType string) error {
	_, err := q.db.ExecContext(ctx, updateCircuitBreakerSuccess, jobType)
	return err
}

const updateJobNextRetry = `-- name: UpdateJobNextRetry :exec
UPDATE jobs SET next_retry_at = ? WHERE id = ?
`

type UpdateJobNextRetryParams struct {
	NextRetryAt sql.NullTime `json:"next_retry_at"`
	ID          int64        `json:"id"`
}

func (q *Queries) UpdateJobNextRetry(ctx context.Context, arg UpdateJobNextRetryParams) error {
	_, err := q.db.ExecContext(ctx, updateJobNextRetry, arg.NextRetryAt, arg.ID)
	return err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users SET avatar_url = ? WHERE id = ?
`

type UpdateUserAvatarParams struct {
	AvatarUrl sql.NullString `json:"avatar_url"`
	ID        int64          `json:"id"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAvatar, arg.AvatarUrl, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = ? WHERE email = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	Email        string `json:"email"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.Email)
	return err
}

const updateUserWithOAuth = `-- name: UpdateUserWithOAuth :one
UPDATE users 
SET provider = ?, provider_id = ?, avatar_url = ?, is_verified = ?
WHERE tenant_id = ? AND email = ?
RETURNING id, tenant_id, email, password_hash, role_id, is_verified, avatar_url, created_at, provider, provider_id
`

type UpdateUserWithOAuthParams struct {
	Provider   sql.NullString `json:"provider"`
	ProviderID sql.NullString `json:"provider_id"`
	AvatarUrl  sql.NullString `json:"avatar_url"`
	IsVerified bool           `json:"is_verified"`
	TenantID   string         `json:"tenant_id"`
	Email      string         `json:"email"`
}

func (q *Queries) UpdateUserWithOAuth(ctx context.Context, arg UpdateUserWithOAuthParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserWithOAuth,
		arg.Provider,
		arg.ProviderID,
		arg.AvatarUrl,
		arg.IsVerified,
		arg.TenantID,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.RoleID,
		&i.IsVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.Provider,
		&i.ProviderID,
	)
	return i, err
}

const upsertCircuitBreakerState = `-- name: UpsertCircuitBreakerState :one
INSERT INTO circuit_breaker_states (job_type, state, failure_count, success_count, last_failure_at, last_success_at, opened_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(job_type) DO UPDATE SET
    state = excluded.state,
    failure_count = excluded.failure_count,
    success_count = excluded.success_count,
    last_failure_at = excluded.last_failure_at,
    last_success_at = excluded.last_success_at,
    opened_at = excluded.opened_at,
    updated_at = CURRENT_TIMESTAMP
RETURNING job_type, state, failure_count, success_count, last_failure_at, last_success_at, opened_at, updated_at
`

type UpsertCircuitBreakerStateParams struct {
	JobType       string       `json:"job_type"`
	State         string       `json:"state"`
	FailureCount  int64        `json:"failure_count"`
	SuccessCount  int64        `json:"success_count"`
	LastFailureAt sql.NullTime `json:"last_failure_at"`
	LastSuccessAt sql.NullTime `json:"last_success_at"`
	OpenedAt      sql.NullTime `json:"opened_at"`
}

func (q *Queries) UpsertCircuitBreakerState(ctx context.Context, arg UpsertCircuitBreakerStateParams) (CircuitBreakerState, error) {
	row := q.db.QueryRowContext(ctx, upsertCircuitBreakerState,
		arg.JobType,
		arg.State,
		arg.FailureCount,
		arg.SuccessCount,
		arg.LastFailureAt,
		arg.LastSuccessAt,
		arg.OpenedAt,
	)
	var i CircuitBreakerState
	err := row.Scan(
		&i.JobType,
		&i.State,
		&i.FailureCount,
		&i.SuccessCount,
		&i.LastFailureAt,
		&i.LastSuccessAt,
		&i.OpenedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEmailVerification = `-- name: UpsertEmailVerification :exec
INSERT INTO email_verifications (email, token, expires_at) 
VALUES (?, ?, ?)
ON CONFLICT(email) DO UPDATE SET 
    token = excluded.token,
    expires_at = excluded.expires_at
`

type UpsertEmailVerificationParams struct {
	Email     string    `json:"email"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) UpsertEmailVerification(ctx context.Context, arg UpsertEmailVerificationParams) error {
	_, err := q.db.ExecContext(ctx, upsertEmailVerification, arg.Email, arg.Token, arg.ExpiresAt)
	return err
}

const upsertJobMetricsHourly = `-- name: UpsertJobMetricsHourly :exec

INSERT INTO job_metrics_hourly (hour, job_type, total_processed, total_succeeded, total_failed, avg_duration_ms, min_duration_ms, max_duration_ms)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(hour, job_type) DO UPDATE SET
    total_processed = job_metrics_hourly.total_processed + excluded.total_processed,
    total_succeeded = job_metrics_hourly.total_succeeded + excluded.total_succeeded,
    total_failed = job_metrics_hourly.total_failed + excluded.total_failed,
    avg_duration_ms = (job_metrics_hourly.avg_duration_ms * job_metrics_hourly.total_processed + excluded.avg_duration_ms) / (job_metrics_hourly.total_processed + 1),
    min_duration_ms = MIN(job_metrics_hourly.min_duration_ms, excluded.min_duration_ms),
    max_duration_ms = MAX(job_metrics_hourly.max_duration_ms, excluded.max_duration_ms),
    updated_at = CURRENT_TIMESTAMP
`

type UpsertJobMetricsHourlyParams struct {
	Hour           string          `json:"hour"`
	JobType        string          `json:"job_type"`
	TotalProcessed sql.NullInt64   `json:"total_processed"`
	TotalSucceeded sql.NullInt64   `json:"total_succeeded"`
	TotalFailed    sql.NullInt64   `json:"total_failed"`
	AvgDurationMs  sql.NullFloat64 `json:"avg_duration_ms"`
	MinDurationMs  sql.NullFloat64 `json:"min_duration_ms"`
	MaxDurationMs  sql.NullFloat64 `json:"max_duration_ms"`
}

// Job Metrics Hourly
func (q *Queries) UpsertJobMetricsHourly(ctx context.Context, arg UpsertJobMetricsHourlyParams) error {
	_, err := q.db.ExecContext(ctx, upsertJobMetricsHourly,
		arg.Hour,
		arg.JobType,
		arg.TotalProcessed,
		arg.TotalSucceeded,
		arg.TotalFailed,
		arg.AvgDurationMs,
		arg.MinDurationMs,
		arg.MaxDurationMs,
	)
	return err
}

const upsertJobTypeConfig = `-- name: UpsertJobTypeConfig :one
INSERT INTO job_type_configs (job_type, timeout_seconds, max_attempts, backoff_base_seconds, backoff_max_seconds, enabled)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(job_type) DO UPDATE SET
    timeout_seconds = excluded.timeout_seconds,
    max_attempts = excluded.max_attempts,
    backoff_base_seconds = excluded.backoff_base_seconds,
    backoff_max_seconds = excluded.backoff_max_seconds,
    enabled = excluded.enabled,
    updated_at = CURRENT_TIMESTAMP
RETURNING job_type, timeout_seconds, max_attempts, backoff_base_seconds, backoff_max_seconds, enabled, updated_at
`

type UpsertJobTypeConfigParams struct {
	JobType            string `json:"job_type"`
	TimeoutSeconds     int64  `json:"timeout_seconds"`
	MaxAttempts        int64  `json:"max_attempts"`
	BackoffBaseSeconds int64  `json:"backoff_base_seconds"`
	BackoffMaxSeconds  int64  `json:"backoff_max_seconds"`
	Enabled            bool   `json:"enabled"`
}

func (q *Queries) UpsertJobTypeConfig(ctx context.Context, arg UpsertJobTypeConfigParams) (JobTypeConfig, error) {
	row := q.db.QueryRowContext(ctx, upsertJobTypeConfig,
		arg.JobType,
		arg.TimeoutSeconds,
		arg.MaxAttempts,
		arg.BackoffBaseSeconds,
		arg.BackoffMaxSeconds,
		arg.Enabled,
	)
	var i JobTypeConfig
	err := row.Scan(
		&i.JobType,
		&i.TimeoutSeconds,
		&i.MaxAttempts,
		&i.BackoffBaseSeconds,
		&i.BackoffMaxSeconds,
		&i.Enabled,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPasswordReset = `-- name: UpsertPasswordReset :exec
INSERT INTO password_resets (email, token_hash, expires_at) 
VALUES (?, ?, ?)
ON CONFLICT(token_hash) DO UPDATE SET 
    email = excluded.email,
    expires_at = excluded.expires_at
`

type UpsertPasswordResetParams struct {
	Email     string    `json:"email"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) UpsertPasswordReset(ctx context.Context, arg UpsertPasswordResetParams) error {
	_, err := q.db.ExecContext(ctx, upsertPasswordReset, arg.Email, arg.TokenHash, arg.ExpiresAt)
	return err
}

const verifyUser = `-- name: VerifyUser :exec
UPDATE users SET is_verified = TRUE WHERE email = ?
`

func (q *Queries) VerifyUser(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, verifyUser, email)
	return err
}
