// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type EmailVerification struct {
	Email     string       `json:"email"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Job struct {
	ID             int64           `json:"id"`
	TenantID       sql.NullString  `json:"tenant_id"`
	Type           string          `json:"type"`
	Payload        json.RawMessage `json:"payload"`
	Status         string          `json:"status"`
	IdempotencyKey sql.NullString  `json:"idempotency_key"`
	AttemptCount   sql.NullInt64   `json:"attempt_count"`
	MaxAttempts    sql.NullInt64   `json:"max_attempts"`
	LastError      sql.NullString  `json:"last_error"`
	RunAt          sql.NullTime    `json:"run_at"`
	CreatedAt      sql.NullTime    `json:"created_at"`
	UpdatedAt      sql.NullTime    `json:"updated_at"`
}

type PasswordReset struct {
	Email     string       `json:"email"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Post struct {
	ID       int64  `json:"id"`
	TenantID string `json:"tenant_id"`
	UserID   int64  `json:"user_id"`
	Title    string `json:"title"`
	Content  string `json:"content"`
}

type PostsIdx struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type ProcessedJob struct {
	JobID       int64     `json:"job_id"`
	ProcessedAt time.Time `json:"processed_at"`
}

type Role struct {
	ID          string          `json:"id"`
	Permissions json.RawMessage `json:"permissions"`
}

type Session struct {
	Token  string  `json:"token"`
	Data   []byte  `json:"data"`
	Expiry float64 `json:"expiry"`
}

type Tenant struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Settings  json.RawMessage `json:"settings"`
	CreatedAt sql.NullTime    `json:"created_at"`
}

type User struct {
	ID           int64          `json:"id"`
	TenantID     string         `json:"tenant_id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	RoleID       string         `json:"role_id"`
	IsVerified   bool           `json:"is_verified"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type Webhook struct {
	ID         int64           `json:"id"`
	Source     string          `json:"source"`
	ExternalID sql.NullString  `json:"external_id"`
	Payload    json.RawMessage `json:"payload"`
	Headers    json.RawMessage `json:"headers"`
	Status     string          `json:"status"`
	CreatedAt  sql.NullTime    `json:"created_at"`
}
