// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AsaasCustomer struct {
	ID        string          `json:"id"`
	TenantID  string          `json:"tenant_id"`
	UserID    sql.NullInt64   `json:"user_id"`
	Email     string          `json:"email"`
	CpfCnpj   sql.NullString  `json:"cpf_cnpj"`
	Name      sql.NullString  `json:"name"`
	AsaasData json.RawMessage `json:"asaas_data"`
	CreatedAt sql.NullTime    `json:"created_at"`
	UpdatedAt sql.NullTime    `json:"updated_at"`
}

type AsaasPayment struct {
	ID            string          `json:"id"`
	TenantID      string          `json:"tenant_id"`
	CustomerID    string          `json:"customer_id"`
	UserID        sql.NullInt64   `json:"user_id"`
	Amount        float64         `json:"amount"`
	BillingType   string          `json:"billing_type"`
	Status        string          `json:"status"`
	DueDate       time.Time       `json:"due_date"`
	PaymentDate   sql.NullTime    `json:"payment_date"`
	InvoiceUrl    sql.NullString  `json:"invoice_url"`
	InvoiceID     sql.NullString  `json:"invoice_id"`
	PixQrCode     sql.NullString  `json:"pix_qr_code"`
	PixCopyPaste  sql.NullString  `json:"pix_copy_paste"`
	AsaasResponse json.RawMessage `json:"asaas_response"`
	CreatedAt     sql.NullTime    `json:"created_at"`
	UpdatedAt     sql.NullTime    `json:"updated_at"`
}

type AsaasSubscription struct {
	ID              string          `json:"id"`
	TenantID        string          `json:"tenant_id"`
	CustomerID      string          `json:"customer_id"`
	UserID          sql.NullInt64   `json:"user_id"`
	PlanValue       float64         `json:"plan_value"`
	BillingType     string          `json:"billing_type"`
	CycleType       string          `json:"cycle_type"`
	Status          string          `json:"status"`
	NextBillingDate sql.NullTime    `json:"next_billing_date"`
	AsaasResponse   json.RawMessage `json:"asaas_response"`
	CreatedAt       sql.NullTime    `json:"created_at"`
	UpdatedAt       sql.NullTime    `json:"updated_at"`
}

type AuditLog struct {
	ID        int64          `json:"id"`
	UserID    sql.NullInt64  `json:"user_id"`
	Action    string         `json:"action"`
	Resource  sql.NullString `json:"resource"`
	Details   sql.NullString `json:"details"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
	TenantID  sql.NullString `json:"tenant_id"`
	RequestID sql.NullString `json:"request_id"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type CircuitBreakerState struct {
	JobType       string       `json:"job_type"`
	State         string       `json:"state"`
	FailureCount  int64        `json:"failure_count"`
	SuccessCount  int64        `json:"success_count"`
	LastFailureAt sql.NullTime `json:"last_failure_at"`
	LastSuccessAt sql.NullTime `json:"last_success_at"`
	OpenedAt      sql.NullTime `json:"opened_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
}

type DeadLetterJob struct {
	ID              int64           `json:"id"`
	JobID           int64           `json:"job_id"`
	OriginalType    string          `json:"original_type"`
	OriginalPayload json.RawMessage `json:"original_payload"`
	ErrorMessage    string          `json:"error_message"`
	AttemptCount    int64           `json:"attempt_count"`
	FailedAt        time.Time       `json:"failed_at"`
	TenantID        sql.NullString  `json:"tenant_id"`
	Metadata        json.RawMessage `json:"metadata"`
}

type EmailVerification struct {
	Email     string       `json:"email"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type FeatureFlag struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Enabled     bool           `json:"enabled"`
	Metadata    sql.NullString `json:"metadata"`
	TenantID    string         `json:"tenant_id"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Job struct {
	ID             int64           `json:"id"`
	TenantID       sql.NullString  `json:"tenant_id"`
	Type           string          `json:"type"`
	Payload        json.RawMessage `json:"payload"`
	Status         string          `json:"status"`
	IdempotencyKey sql.NullString  `json:"idempotency_key"`
	AttemptCount   sql.NullInt64   `json:"attempt_count"`
	MaxAttempts    sql.NullInt64   `json:"max_attempts"`
	LastError      sql.NullString  `json:"last_error"`
	RunAt          sql.NullTime    `json:"run_at"`
	NextRetryAt    sql.NullTime    `json:"next_retry_at"`
	WorkerID       sql.NullString  `json:"worker_id"`
	StartedAt      sql.NullTime    `json:"started_at"`
	CompletedAt    sql.NullTime    `json:"completed_at"`
	TimeoutSeconds sql.NullInt64   `json:"timeout_seconds"`
	Priority       sql.NullInt64   `json:"priority"`
	CreatedAt      sql.NullTime    `json:"created_at"`
	UpdatedAt      sql.NullTime    `json:"updated_at"`
}

type JobMetricsHourly struct {
	Hour           string          `json:"hour"`
	JobType        string          `json:"job_type"`
	TotalProcessed sql.NullInt64   `json:"total_processed"`
	TotalSucceeded sql.NullInt64   `json:"total_succeeded"`
	TotalFailed    sql.NullInt64   `json:"total_failed"`
	AvgDurationMs  sql.NullFloat64 `json:"avg_duration_ms"`
	MinDurationMs  sql.NullFloat64 `json:"min_duration_ms"`
	MaxDurationMs  sql.NullFloat64 `json:"max_duration_ms"`
	UpdatedAt      sql.NullTime    `json:"updated_at"`
}

type JobTypeConfig struct {
	JobType            string       `json:"job_type"`
	TimeoutSeconds     int64        `json:"timeout_seconds"`
	MaxAttempts        int64        `json:"max_attempts"`
	BackoffBaseSeconds int64        `json:"backoff_base_seconds"`
	BackoffMaxSeconds  int64        `json:"backoff_max_seconds"`
	Enabled            bool         `json:"enabled"`
	UpdatedAt          sql.NullTime `json:"updated_at"`
}

type PasswordReset struct {
	Email     string       `json:"email"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Post struct {
	ID       int64  `json:"id"`
	TenantID string `json:"tenant_id"`
	UserID   int64  `json:"user_id"`
	Title    string `json:"title"`
	Content  string `json:"content"`
}

type PostsIdx struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type ProcessedJob struct {
	JobID       int64     `json:"job_id"`
	ProcessedAt time.Time `json:"processed_at"`
}

type ProcessedWebhookEvent struct {
	EventSource string        `json:"event_source"`
	EventID     string        `json:"event_id"`
	WebhookID   sql.NullInt64 `json:"webhook_id"`
	ProcessedAt time.Time     `json:"processed_at"`
}

type Role struct {
	ID          string          `json:"id"`
	Permissions json.RawMessage `json:"permissions"`
}

type Session struct {
	Token  string  `json:"token"`
	Data   []byte  `json:"data"`
	Expiry float64 `json:"expiry"`
}

type Tenant struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Settings  json.RawMessage `json:"settings"`
	CreatedAt sql.NullTime    `json:"created_at"`
}

type User struct {
	ID           int64          `json:"id"`
	TenantID     string         `json:"tenant_id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	RoleID       string         `json:"role_id"`
	IsVerified   bool           `json:"is_verified"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	Provider     sql.NullString `json:"provider"`
	ProviderID   sql.NullString `json:"provider_id"`
}

type Webhook struct {
	ID         int64           `json:"id"`
	Source     string          `json:"source"`
	ExternalID sql.NullString  `json:"external_id"`
	Payload    json.RawMessage `json:"payload"`
	Headers    json.RawMessage `json:"headers"`
	Status     string          `json:"status"`
	CreatedAt  sql.NullTime    `json:"created_at"`
}
